### PR TITLE
Mvw/upstream

### PR DESCRIPTION
**Pull request by mvwieringen**
Pull request including change to brace layout as discussed via email.

### CODE REVIEW

**Comment by mvwieringen** [comment]
Unit tests should now work again but github was kind of slow this morning so circleci could
not checkout the new patch. I cannot find an obvious place to retrigger the circleci stuff.

**Comment by DavidPineauScality** [comment]
I triggered a rebuild, it might be because you do not have write permissions to the repo (and thus to the circle ci project)

**Comment by mvwieringen** [comment]
Seems its now all green again.

**Comment by DavidPineauScality** [comment]
Looks good for me, but I need to take some time and check that it compiles properly with some projects that depend on it before I merge it :)

**Pull request closed without merging**
