### PR TITLE
fix resource_ue and side effect

### PR DESCRIPTION
**Pull request by QuentinPerez**

### CODE REVIEW

**Comment by Joacchim** [comment]
If the previous comment is adressed, the path will be fine for me.

**Comment by QuentinPerez** [comment]
Changed :+1:

**Comment by Joacchim** [comment]
Looks good, it will be merged later on (for internal needs)

**Comment by QuentinPerez** [comment]
any news ?

**Comment by DavidPineauScality** [comment]
Hello, sorry I haven't had time to double-check whether this change had any impact on our current binaries building that are using it. That's my last step before merging.

**Pull request closed without merging**
